# frozen_string_literal: true

source 'https://rubygems.org'

# frozen_string_literal: true

# gem "rails"
group :development, :test do
  # gem 'rubocop'
  # gem 'rubocop-rails'
  # or gem 'rubocop-rspec' depending on your test suite
end
